Add menu functionality
S-imba/My-Portfolio---Mobile-Version pull request #7
Opened 2022-04-04 13:55 UTC by S-imba

In this pull request, the following have been done:

- When the user clicks (or taps) the hamburger button, the mobile menu appears.
- When the user clicks (or taps) the close (X) button, the mobile menu disappears.
- When the user clicks (or taps) any of the mobile menu options, the mobile menu disappears.
- When the user clicks (or taps) any of the mobile menu options, a correct part of the page is displayed.

2022-04-04 14:36 UTC, prolajumokeoni commented
- [ ] Please fix the horizontal scroll on your website because horizontally scrolling for pages with lots of text or  buttons to click may not be a good experience  form users currently a user has to  scroll horizontally to see the close button, to fix this check the width and margins used in your project, here  is a video to show you what I see on your website ⬇️ 

https://user-images.githubusercontent.com/69638013/161566915-1d0dc3eb-4de2-4a88-abf7-3c61f860eede.mp4

2022-04-04 14:37 UTC, prolajumokeoni requested changes
Hi Team 👋🏿 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ GitHub flow was correctly used
✔️  Good design



## Required Changes ♻️
_Check the comments under the review._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-04 14:37 UTC, prolajumokeoni commented on index.html
> +            </div>
Figma Design          |  Your design     
:-------------------------:|:-------------------------:
![Screenshot_5](https://user-images.githubusercontent.com/69638013/161509772-8d06045b-1c2e-429a-a19f-5a13841832a9.png) |  ![Screenshot_8](https://user-images.githubusercontent.com/69638013/161565280-b2e9d5af-bd8a-45bf-a3ca-288903e2f58b.png)


- [x] Kindly make the background blurry when the mobile navigation is open, this will make the mobile nav text more visible to the users 👍🏿 
- [x] It would be better for the background not to be scrollable when the mobile nav is open 👍🏿 

- Adding these functionalities will make your design good and look exactly like the Figma design, great job so far 💪🏿

2022-04-05 12:36 UTC, elyor-doniyorov requested changes
Hi @S-imba, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Suggested changes
- [ ] Well done implementing the changes, however, you still need to fix the horizontal scroll gap as requested by the previous reviewer. Take a look at the below screenshot of your app and fix it please 👇 
![Screenshot (245)](https://user-images.githubusercontent.com/67087664/161754752-501ad2a7-d0f1-469c-aa87-0fee7b8be08f.png)




Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-04-06 07:34 UTC, Deepakdanger approved these changes
Hi @S-imba, 

### Status: Approved ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚢 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] After clicking on the hamburger menu in the **mobile** version, The mobile-menu design appears, now switching to the **desktop** version should remove this mobile menu.KIndly fix this.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-06 07:38 UTC, S-imba commented
@Deepakdanger thank you for approving the pull request
I will work on the requested changes

2022-04-06 07:39 UTC, merged